[tool.poetry]
name = "llm2"
version = "2.0.0"
description = ""
authors = ["Marcel Klehr <mklehr@gmx.net>"]
license = "AGPL-3.0"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.8.2"
fastapi = "^0.111.0"
nc-py-api = {extras = ["app"], version = "^0.16.0"}
langchain = "^0.1.0"
llama-cpp-python = "0.2.76"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
